# vim:ft=ansible:
---
- name: install and start apache
  hosts: all
  become: yes
  
  tasks:
    - name: httpd package is present
      apt:
        name: apache2
        state: latest

    - name: latest index file is present
      template:
        src: files/{{ stage }}_index.html
        dest: /var/www/html/

    - name: httpd is started
      service:
        name: apache2
        state: started

