# vim:ft=ansible:
---
- name: handler playbook
  hosts: localhost
  become: true

  tasks:
    - name: Ensure apache is present
      apt:
        name: apache2
        state: latest
      notify: restart_apache
  
  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
