---
- hosts: all
  become: true

  tasks:
    - name: Get all repo files 
      ansible.builtin.find:
        paths: /etc/yum.repos.d
        patterns: "CentOS-*"
      register: repo_glob

    - name: Disable mirror list in all repo files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "mirrorlist"
        replace: "#mirrorlist"
      with_items:
        - "{{ repo_glob.files }}"

    - name: Change baseurl from centos.org to epel.cloud
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "#baseurl=http://mirror.centos.org"
        replace: "baseurl=http://vault.epel.cloud"
      with_items:
        - "{{ repo_glob.files }}"
