---
# defaults file for roles/common
common_packages:
  - "chrony"
  - "vim-enhanced"
  - "git"
  - "unzip"
  - "epel-release"

ntp_servers:
  - "0.de.pool.ntp.org"
  - "1.de.pool.ntp.org"
  - "2.de.pool.ntp.org"
  - "3.de.pool.ntp.org"

users:
  - {
    name: "lamp",
    group: "lamp",
    state: "present",
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}",
  }
