---
- name: setup wireguard client
  hosts: localhost
  connection: local
  become: yes
  handlers:
    
  # Restarts WireGuard interface, loading any new config and running PostUp
  # commands in the process. Notify this handler on client config changes.
  - name: restart_wireguard
    shell: wg-quick down wg0; wg-quick up wg0
    args:
      executable: /bin/bash
  
  tasks:
  
  - name: install wireguard package
    apt:
      name: wireguard
      state: present
      update_cache: yes

  - name: generate private key
    shell:
      cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > publickey
      chdir: /etc/wireguard
      creates: /etc/wireguard/publickey

  - name: get public key
    command: cat /etc/wireguard/publickey
    register: publickey_contents
    changed_when: False

  # Save pubkey as a fact, so we can use it to template wg0.conf for the server
  - name: set public key fact
    set_fact:
      pubkey: "{{ publickey_contents.stdout }}"

  - name: create client wireguard config
    template:
      dest: /etc/wireguard/wg0.conf
      src: client_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'
    notify: reload_wireguard

- name: setup wireguard server
  hosts: vpn_server
  become: true
  vars:
    server_privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64323439663664666133323939353536626530663664666232323831633661303063303937383563
          3236356634333439323834643638383835363361306636300a623239313466303763373238383837
          34346565363932326133653339646635396533383338633937643139396565353063316334346437
          3037663662303365660a303136656365356463366365343838636236353431396564333638323530
          38613061636362316436326339623933633961323939323662623163653131343766663665396666
          6335613238333165666435316337326331663334363737396534
    server_pubkey: T5UDMUdCcr6gBzMsclRAfsSNf3EOxT988KIshVr14W8=
  handlers:
  # Restarts WireGuard interface, loading any new config and running PostUp
  # commands in the process. Notify this handler on client config changes.
  - name: reload_wireguard
    shell: wg syncconf wg0 <(wg-quick strip wg0)
    args:
      executable: /bin/bash

  tasks:
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html  
  - name: install wireguard
    apt:
      name: wireguard
      state: present
      update_cache: yes
  
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  - name: create server wireguard config
    template:
      dest: /etc/wireguard/wg0.conf
      src: server_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'
    notify: restart_wireguard

  # https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html
  - name: enable and persist ip forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      sysctl_set: yes
      reload: yes
  
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
  - name: start wireguard and enable on boot
    systemd:
      name: wg-quick@wg0
      enabled: yes
      state: started

- name: start vpn on client
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Start Wireguard
    command: wg-quick up wg0
