---
- hosts: all
  become: true

  vars_files:
    - vars/certbot.yml
    - vars/firewall.yml
    - vars/nginx.yml
    - vars/self-signed-cert.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600

    - name: Install dependencies for pyopenssl.
      ansible.builtin.apt: name=libssl-dev state=present

  roles:
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.nginx
    - geerlingguy.certbot

  tasks:
    - ansible.builtin.import_tasks: tasks/common.yml
    - ansible.builtin.import_tasks: tasks/self-signed-cert.yml

    - name: Ensure docroots exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: "0755"
      with_items:
        - /var/www/nobj.de
        - /var/www/clients.nobj.de
