---
- hosts: all
  become: True

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      apt: update_cache=yes cache_valid_time=600

    - name: Install dependencies for pyopenssl.
      apt: name=libssl-dev state=present

  roles:
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.nginx
    - geerlingguy.certbot

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/self-signed-cert.yml

    - name: Ensure docroots exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "www-data"
        group: "www-data"
      with_items:
        - /var/www/nobj.de
        - /var/www/clients.nobj.de
