---
- name: Creates letsencrypt certificate for clients.nobj.de
  hosts: dev
  become: true
  debugger: on_failed

  vars:
    domain: p2022.clients.nobj.de

    certbot_admin_email: admin@new-objects.com
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: [] # TODO: ???
    certbot_certs:
      - domains:
          - "{{ domain }}"

    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{ domain }}"
        root: "/var/www/{{ domain }}"
        index: "index.php index.html index.htm"
        state: present
        template: "{{ nginx_vhost_template }}" # TODO: ???
        filename: "certbot_{{ domain }}.conf"
        extra_parameters: |
          location / {
            try_files $uri $uri/ /index.php$is_args$args;
          }
          location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass localhost:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
          }
          ssl_certificate     /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNull:!MD5;

    php_version: "8.1"
    php_packages:
      - php8.1
      - php8.1-gd
      - php8.1-xml
      - php8.1-fpm
    php_webserver_daemon: nginx
    php_enable_php_fpm: true

  roles:
    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-versions

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

    - name: Install cron (Debian)
      ansible.builtin.apt:
        name: cron
        state: present

    - name: Flush handlers in case any configs have changed.
      ansible.builtin.meta: flush_handlers

    - name: Test secure connection to SSL domain
      ansible.builtin.uri:
        url: https://{{ domain }}
        status_code: 200
      delegate_to: localhost
      become: false
