---
roles:
  - name: geerlingguy.certbot
    version: 5.0.2

  - name: geerlingguy.nginx
    version: 3.1.3

  - name: geerlingguy.php
    version: 4.8.0

  - name: geerlingguy.php-versions
    version: 5.0.1